package me.lam.model;
// Generated Dec 29, 2020 2:12:33 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * User1 generated by hbm2java
 */
@Entity
@Table(name = "USER1")
public class User1 implements java.io.Serializable {

	private int id;
	private String firstName;
	private String password;
	private String lastName;
	private String email;
	private String sex;
	private Byte active;
	private Integer status;

	public User1() {
	}

	public User1(int id) {
		this.id = id;
	}

	public User1(int id, String firstName, String password, String lastName, String email, String sex, Byte active,
			Integer status) {
		this.id = id;
		this.firstName = firstName;
		this.password = password;
		this.lastName = lastName;
		this.email = email;
		this.sex = sex;
		this.active = active;
		this.status = status;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "FirstName", length = 45)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "Password", length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "LastName", length = 45)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "Email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "Sex", length = 45)
	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	@Column(name = "Active")
	public Byte getActive() {
		return this.active;
	}

	public void setActive(Byte active) {
		this.active = active;
	}

	@Column(name = "Status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
