package me.lam.model;
// Generated Dec 30, 2020 11:58:46 AM by Hibernate Tools 5.2.10.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * UserType generated by hbm2java
 */
@Entity
@Table(name = "USER_TYPE")
public class UserType implements java.io.Serializable {

	private int id;
	private String type;

	@JsonBackReference
	@JsonIgnoreProperties(value = { "hibernateLazyInitializer", "handler", "fieldHandler" })
	private Set<User> users = new HashSet<User>(0);

	public UserType() {
	}

	public UserType(int id) {
		this.id = id;
	}

	public UserType(int id, String type, Set<User> users) {
		this.id = id;
		this.type = type;
		this.users = users;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "type", length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userType")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
